### ISSUE TITLE
Mode, Fan_speed_list values

### ISSUE THREAD

**Issue by timota** [rikman122/tuya-vacuum-card#1]
During initial testing of your card, found that you have hardcoded fan_speed_list values.

```js
en: {
    smart: "Smart",
    standby: "Standby",
    chargego: "Go Charge",
    wall_follow: "Wall Follow",
    spiral: "Spiral",
    single: "Spot",
    low: "Low",
    normal: "Normal",
    high: "High"
},
```

as an example, my vacuum has different mode names (modes and fan_speed_list)

```yaml
      - platform: vacuum
        friendly_name: Robot Vacuum
        id: 5
        idle_status_value: "standby,sleep,paused"
        powergo_dp: 2
        docked_status_value: "charging,charge_done"
        returning_status_value: "goto_charge"
        battery_dp: 6
        mode_dp: 3
        modes: "chargego,smart,wall_follow,spiral,partial_bow,mop"
        fan_speed_dp: 14
        fan_speeds: "gentle,normal,strong"
        clean_time_dp: 16
        clean_area_dp: 17
```

probably it will be good idea to fetch those from vacuum itself or define them in card configuration. 

Regards
